In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\GNANASEKARAN\\OneDrive\\Documents\\Python Project\\Operational_Transactions.csv")

In [3]:
df.shape

(45000, 12)

In [4]:
df.head()

,transaction_id,order_date,customer_id,customer_name,region,product_category,quantity,unit_price,total_amount,payment_mode,order_status,created_timestamp
0,300000,NaN,4063,Customer_5122,North,Groceries,4,2207.14,8828.56,Debit Card,NaN,10:22.0
1,300001,NaN,3810,Customer_3950,north,Electronics,5,1686.11,10136.24,UPI,Completed,10:22.0
2,300002,04-04-2024,1159,Customer_4348,NaN,Groceries,3,3304.23,9912.69,Debit Card,Cancelled,10:22.0
3,300003,25-05-2023,1471,Customer_5527,West,Groceries,5,4670.31,23351.55,Debit Card,Cancelled,10:22.0
4,300004,08-06-2023,4457,Customer_3665,north,Clothing,5,717.75,3588.75,credit card,Pending,10:22.0

In [5]:
df.isna().sum()

transaction_id          0
order_date           3597
customer_id             0
customer_name           0
region               6330
product_category        0
quantity                0
unit_price              0
total_amount            0
payment_mode         7443
order_status         8995
created_timestamp       0
dtype: int64

In [6]:
df.replace('', np.nan, inplace=True)

In [7]:
df.isna().sum()

transaction_id          0
order_date           3597
customer_id             0
customer_name           0
region               6330
product_category        0
quantity                0
unit_price              0
total_amount            0
payment_mode         7443
order_status         8995
created_timestamp       0
dtype: int64

In [8]:
df.duplicated(subset='transaction_id').sum()

3000

In [9]:
df[df.duplicated(subset='transaction_id', keep=False)].sort_values('transaction_id').head(10)

,transaction_id,order_date,customer_id,customer_name,region,product_category,quantity,unit_price,total_amount,payment_mode,order_status,created_timestamp
58,300058,04/24/2024,4122,Customer_4559,NaN,Electronics,4,410.84,1643.36,Cash,NaN,10:22.0
42646,300058,04/24/2024,4122,Customer_4559,NaN,Electronics,4,410.84,1643.36,Cash,NaN,10:22.0
67,300067,09/25/2023,3607,Customer_4102,north,Groceries,2,4490.03,8980.06,Credit Card,Completed,10:22.0
43796,300067,09/25/2023,3607,Customer_4102,north,Groceries,2,4490.03,8980.06,Credit Card,Completed,10:22.0
68,300068,10-04-2023,4498,Customer_1559,East,Clothing,4,2821.64,11286.56,NaN,Cancelled,10:22.0
43138,300068,10-04-2023,4498,Customer_1559,East,Clothing,4,2821.64,11286.56,NaN,Cancelled,10:22.0
78,300078,05/21/2023,3010,Customer_2391,South,Clothing,4,4749.88,18999.52,Credit Card,completed,10:22.0
42636,300078,05/21/2023,3010,Customer_2391,South,Clothing,4,4749.88,18999.52,Credit Card,completed,10:22.0
44567,300093,11/13/2022,3471,Customer_5547,NaN,Electronics,3,4155.80,12467.40,NaN,completed,10:22.0
93,300093,11/13/2022,3471,Customer_5547,NaN,Electronics,3,4155.80,12467.40,NaN,completed,10:22.0

In [10]:
df = df.drop_duplicates(subset='transaction_id', keep='first')

In [11]:
df.duplicated(subset='transaction_id').sum()

0

In [12]:
df['region'].value_counts(dropna=False)

SOUTH     6113
South     6018
North     6011
East      6005
West      5979
north     5962
NaN       5912
Name: region, dtype: int64

In [13]:
# Standardize text columns
text_cols = ['region', 'payment_mode', 'order_status', 'product_category']

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [14]:
df['region'].value_counts(dropna=False)

South    12131
North    11973
East      6005
West      5979
NaN       5912
Name: region, dtype: int64

In [15]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

C:\Users\GNANASEKARAN\AppData\Local\Temp\ipykernel_36460\2225214990.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [16]:
df['order_date'].head(10)

0          NaT
1          NaT
2   2024-04-04
3   2023-05-25
4   2023-08-06
5   2022-07-04
6   2023-02-27
7   2022-11-29
8   2022-07-15
9   2024-05-24
Name: order_date, dtype: datetime64[ns]

In [17]:
df['order_date'].isna().sum()

3382

In [18]:
df[['quantity', 'unit_price', 'total_amount']].describe()

           quantity    unit_price  total_amount
count  42000.000000  42000.000000  42000.000000
mean       3.008762   2548.962045   7682.222678
std        1.417382   1411.588797   5956.072518
min        1.000000    100.030000     85.600000
25%        2.000000   1332.902500   2895.990000
50%        3.000000   2547.360000   6072.360000
75%        4.000000   3777.655000  11394.377500
max        5.000000   4999.860000  31545.930000

In [19]:
df[df['total_amount'] != df['quantity'] * df['unit_price']].head()

,transaction_id,order_date,customer_id,customer_name,region,product_category,quantity,unit_price,total_amount,payment_mode,order_status,created_timestamp
1,300001,NaT,3810,Customer_3950,North,Electronics,5,1686.11,10136.24,Upi,Completed,10:22.0
3,300003,2023-05-25,1471,Customer_5527,West,Groceries,5,4670.31,23351.55,Debit Card,Cancelled,10:22.0
6,300006,2023-02-27,3195,Customer_185,East,Electronics,3,4498.48,13495.44,Debit Card,Pending,10:22.0
7,300007,2022-11-29,1056,Customer_2087,South,Electronics,3,590.56,1771.68,Credit Card,Cancelled,10:22.0
9,300009,2024-05-24,4034,Customer_2143,East,Electronics,5,4339.63,28102.17,Upi,Completed,10:22.0

In [20]:
df['order_date'].head(10)

0          NaT
1          NaT
2   2024-04-04
3   2023-05-25
4   2023-08-06
5   2022-07-04
6   2023-02-27
7   2022-11-29
8   2022-07-15
9   2024-05-24
Name: order_date, dtype: datetime64[ns]

In [21]:
df['region'] = df['region'].fillna('Unknown')

In [22]:
df['region'].value_counts(dropna=False)

South      12131
North      11973
East        6005
West        5979
Unknown     5912
Name: region, dtype: int64

In [23]:
df['region'] = df['region'].fillna('Unknown')

In [24]:
df['payment_mode'] = df['payment_mode'].fillna('Unknown')
df['order_status'] = df['order_status'].fillna('Unknown')

df[['payment_mode', 'order_status']].isna().sum()

payment_mode    0
order_status    0
dtype: int64

In [25]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=True,
    errors='coerce'
)

df['order_date'].isna().sum()

3382

In [26]:
invalid_amounts = df[
    df['total_amount'] != (df['quantity'] * df['unit_price'])
]

invalid_amounts.shape

(9254, 12)

In [27]:
# Round amounts to 2 decimals for reporting
df['unit_price'] = df['unit_price'].round(2)
df['total_amount'] = df['total_amount'].round(2)

In [28]:
df.to_csv('operational_transactions_cleaned_python.csv', index=False)

In [29]:
df.shape
df.isna().sum()
df.duplicated(subset='transaction_id').sum()

0

In [30]:
invalid_amounts.to_csv(
    'invalid_transaction_amounts.csv',
    index=False
)

In [31]:
# Final dataset health check
print("Shape:", df.shape)
print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate transaction_id count:")
print(df.duplicated(subset='transaction_id').sum())

print("\nData types:")
print(df.dtypes)

Shape: (42000, 12)

Missing values:
transaction_id          0
order_date           3382
customer_id             0
customer_name           0
region                  0
product_category        0
quantity                0
unit_price              0
total_amount            0
payment_mode            0
order_status            0
created_timestamp       0
dtype: int64

Duplicate transaction_id count:
0

Data types:
transaction_id                int64
order_date           datetime64[ns]
customer_id                   int64
customer_name                object
region                       object
product_category             object
quantity                      int64
unit_price                  float64
total_amount                float64
payment_mode                 object
order_status                 object
created_timestamp            object
dtype: object

In [32]:
df.to_csv("C:\\Users\\GNANASEKARAN\\OneDrive\\Documents\\Python Project\\operational_transactions_cleaned_final.csv", index=False)